### ISSUE TITLE
"upload is empty", but actually not

### ISSUE THREAD

**Issue by KermanX** [codecov/Codecov-user-feedback#22]
### Codecov.io shows:
![image](https://user-images.githubusercontent.com/63178754/166226632-79b107d5-a2a4-4ed6-822a-db6e87c91f86.png)
![image](https://user-images.githubusercontent.com/63178754/166226687-40db2c89-4339-4cb9-a642-e035db66c5b0.png)

### Upload:
https://api.codecov.io/upload/gh/UniCoderGroup/ucon/download?path=v4/raw/2022-05-02/D435E04F1947C79FCEAC1991EB1239CD/4550549c8946359e2c0ecdd5f3154eaff78299f1/b01d69c8-0c88-41ef-9fc8-4aefd15afcd4.txt

> It is not empty!

### Github action outputs:
> `"status":"success"`

![image](https://user-images.githubusercontent.com/63178754/166226773-8e1a3cd3-9929-4b80-b319-932c9f5176b7.png)

### Github action code:
```yaml
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

      # Install monorepo dependencies
    - run: npm ci
      # Install all dependencies and link packages
    - run: lerna bootstrap
      # Build climo
    - run: tsc --build
      working-directory: ./scripts
      # Run test in all packages
    - run: node ./dist/index.js run test "*"
      working-directory: ./scripts
      # Upload coverage to Codecov.io
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
```

### codecov.yml
no

### REPO
https://github.com/UniCoderGroup/ucon
